# Generated by Django 5.2.7 on 2025-10-30 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_image_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', verbose_name='Тип голоса'),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', verbose_name='Тип голоса'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='myapp.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='answerlike',
            index=models.Index(fields=['type'], name='myapp_answe_type_0f66ee_idx'),
        ),
        migrations.AddIndex(
            model_name='questionlike',
            index=models.Index(fields=['type'], name='myapp_quest_type_2550b2_idx'),
        ),
    ]
