# Generated by Django 5.2.7 on 2025-11-07 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_answerlike_type_questionlike_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='myapp.answer', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['rating'], name='myapp_answe_rating_783306_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['author', 'created_at'], name='myapp_answe_author__b544d6_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['rating'], name='myapp_quest_rating_be7904_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['author', 'created_at'], name='myapp_quest_author__dd6f23_idx'),
        ),
    ]
