# Generated by Django 4.2.16 on 2025-11-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_answer_rating_question_rating_alter_answer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=10, verbose_name='Тип голоса'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=10, verbose_name='Тип голоса'),
        ),
    ]
