# Generated by Django 4.2.16 on 2025-12-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_answerlike_type_alter_questionlike_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
