# Generated by Django 4.2.16 on 2025-12-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['title'], name='myapp_quest_title_b92cca_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['content'], name='myapp_quest_content_56fee3_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='myapp_tag_name_171f7c_idx'),
        ),
    ]
