# Generated by Django 4.2.16 on 2025-12-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_question_myapp_quest_title_b92cca_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Содержание вопроса'),
        ),
    ]
