version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: my-django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Django:/app  # ← монтируем папку Django в /app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=myapp_db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - PYTHONPATH=/app  # ← важно для импортов
    depends_on:
      - postgres

volumes:
  postgres_data: