proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=my_cache:10m;

upstream questionproject {
    server web:8000;
}

server {
    listen 80;
    server_name questionproject.localhost;
    
    gzip on;
    gzip_types 
        image/svg+xml 
        image/jpeg 
        image/png 
        image/gif
        text/css
        application/javascript;
    gzip_vary on;
    gzip_min_length 1024;

    access_log /var/log/nginx/questionproject_access.log;
    error_log /var/log/nginx/questionproject_error.log;

    location /static/ {
        alias /app/static/;
        expires 24h;
        access_log off;
        add_header Cache-Control "public";
    }

    location /media/ {
        alias /app/media/;
        expires 24h;
        access_log off;
        add_header Cache-Control "public";
    }

    location /test_no_cashe/ {
        proxy_pass http://questionproject/test/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /test_with_cashe/ {
        proxy_pass http://questionproject/test/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache my_cache;
        proxy_cache_valid 200 5m;
        add_header X-Cache-Status $upstream_cache_status;
    }

    location / {
        proxy_pass http://questionproject;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache my_cache;
        proxy_cache_valid 200 5m;
        add_header X-Cache-Status $upstream_cache_status;
    }
}