# Generated by Django 4.2.16 on 2025-12-03 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mngusersapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Никнейм')),
                ('avatar', models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to=mngusersapp.models.user_profile_image_path, verbose_name='Изображение профиля')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='mngusersapp_created_445e4f_idx')],
            },
        ),
    ]
